"""OM-C 14-CAT-C-LFTZ — La Môle."""

DETAIL = {
    "category": "Cat C",
    "headline": "Saint-Tropez · visual only · RWY 24 in / RWY 06 out · AFIS · DSAC authorisation",
    "pdf_section": "OM-C 14-CAT-C-LFTZ",
    "qualification": [
        "PIC: aircraft flight training required (TRI approved by DSAC/SE).",
        "SIC: OM-C brief familiarisation.",
        "Type-related qualification: yes.",
        "Self-briefing: not permitted.",
        "Phenom 300 and CE-680A Latitude only.",
        "PIC must operate as PF to/from La Môle within 2 months of initial qualification.",
        "To remain qualified: operate to/from LFTZ within 12 months of last visit.",
        "Each operation extends validity 12 months from date of operation.",
        "PF shall hold current AHQ.",
    ],
    "revalidation": [
        "OM-C briefing review prior to every flight.",
        "In-flight familiarisation: yes for initial and revalidation.",
        "PIC must fly as PF within 2 months of initial qual; revisit within 12 months.",
    ],
    "limitations": [
        "DAY ONLY operations.",
        "Landing RWY 24 only; takeoff RWY 06 only.",
        "PF for approach, landing and takeoff shall be PIC on LHS.",
        "Normal CAT AIR-OPS performance calculations mandatory.",
        "Takeoff/landing prohibited if:",
        "  — Wind outside sector 040°–070°: avg > 13 kt or max > 16 kt.",
        "  — Wind inside sector 040°–070°: avg > 15 kt.",
        "  — No AFIS wind available.",
        "  — Outside AFIS hours.",
        "  — Wet or contaminated runway.",
        "  — OEI.",
        "  — Inop equipment reducing performance (Latitude: both thrust reversers required).",
        "Approach prohibited: wet runway, OEI, inop performance equipment.",
    ],
    "threats": [
        "Extensive visual manoeuvring for arrival and departure.",
        "Weather minima must be met for entire visual portion.",
        "Westerly winds > 10 kt: rotor and windshear risk on RWY 24 landing.",
        "Common wind split: 240° at threshold 24 vs 140° at mid-runway — drives wind restrictions.",
        "Mistral (winter) and sea-breeze (summer) — disruption likely 1200–1700 local.",
        "Busy VFR traffic (light aircraft, helicopters) near EM and STP VOR.",
        "Windshear below 300 ft AAL: low energy state — continued sink possible during escape.",
    ],
    "overview": (
        "Category C airport near Saint Tropez. NetJets has special DSAC/SE authorisation for procedures in this OM-C. "
        "Procedures minimise noise and avoid adjacent airspace."
    ),
    "operational_general": [
        "Map display: suitable range with adjacent/restricted airspace and TAWS overlay (Latitude) on MFD.",
        "Note prohibited, restricted and danger areas from EFB.",
        "ATIS by phone: +33 4 94 54 76 62.",
        "Select Hyeres (LFTH) approach on Com 2 spare VHF.",
    ],
    "weather": ["Arrival and departure: 5 km vis, 2500 ft ceiling (Cat B)."],
    "approaches": [
        {
            "name": "9.2 Visual approach RWY 24 via EM (Port Grimaud)",
            "expanded": True,
            "procedure": [
                "RWY 24 ONLY. Visual via EM (warehouse SE of Port Grimaud beach).",
                "From east via Golfe de Saint-Tropez: stay centre of bay to minimise noise.",
                "Report visual over EM at 2500 ft, fully configured.",
                "Leave EM: track 234°, remain SE of highway D98 until abeam Cogolin.",
                "EM to threshold ~5.8 NM; STP to threshold ~5 NM; ~900 fpm descent from EM.",
                "Stable approach criteria at 500 ft AAL; wings level by 300 ft.",
                "Continue when windsock clearly visible; visual assessment for continue/go-around.",
                "Config: flaps full, gear down, Vref+5 kt.",
                "Ask AFIS if other aircraft reported windshear on initial contact.",
                "OEI before abeam Cogolin: left to STP, climb 2500 ft VMC.",
                "OEI after abeam Cogolin: go-around on prescribed ground track.",
                "OEI below 300 ft: land or go-around if destabilised.",
                "Windsock left abeam threshold 24 — best touchdown wind indication.",
                "'Calm' wind = up to 3 kt from any direction.",
            ],
        },
        {
            "name": "9.1 General / VOR A cloud-break",
            "procedure": [
                "VOR A may be used as cloud-break to become visual at/above 2500 ft.",
                "If VMC: immediate right turn up to 3400 ft, VMC below cloud, cancel IFR, VFR to STP, east to coast, position to EM.",
                "If no VMC: published VOR A MAP, coordinate diversion.",
            ],
        },
        {
            "name": "9.3 VMC go-around / balked landing",
            "procedure": [
                "Remain VMC. Overfly runway on runway track until abeam apron.",
                "Right abeam apron, centre of La Môle valley (track 290°).",
                "Abeam water treatment plant (right), left to avoid village, follow D98 (~track 250°).",
                "Clean up: 1100 ft AEO or 1600 ft OEI.",
                "Climb 3400 ft if weather permits, else min 2500 ft.",
                "At 10 DME STP along valley, left turn to intercept R250 inbound STP.",
                "Avoid built-up areas ~5 DME STP; proceed visual to EM or alternate.",
                "Report intentions to AFIS ASAP. PDCS performance.",
            ],
        },
    ],
    "departure": [
        "RWY 06 only. Static takeoff, full runway length.",
        "Do NOT fly IFR SIDs from Jeppesen — OEI climb gradients cannot be met.",
        "Latitude at 22,000 lb MTOM: min 12% climb gradient (max 30°C OAT, flaps 1).",
        "VFR departure: runway HDG 061°.",
        "Abeam factory (right), turn LEFT ~036°, centre of valley toward coast (EM direction).",
        "Passing 1500 ft turn right VMC to STP VOR for IFR join.",
        "Standard flap retraction per OM-B; climb 150 kt to max 3400 ft VMC until cleared to controlled airspace.",
        "Flaps per PDCS; max takeoff weights per PDCS.",
        "OEI RWY 06: abeam factory turn left follow valley; at 3.3 DME STP (not below 1000 ft) turn right to STP.",
        "Min acceleration altitude 1559 ft (PDCS). Climb max 3400 ft VMC below cloud.",
        "Critical obstacles and OEI corridor — see OM-C track table for V2 100–120 kt.",
    ],
    "ground": ["Refer to Jeppesen."],
    "charts": [
        "Section 7 — airport overview (factory reference for departure/OEI).",
        "Engine failure procedure RWY 06 track pictures.",
        "OEI corridor RWY 06 critical obstacles table.",
    ],
}
